app = 'openrailwaymap'
primary_region = 'ams'

[build]
  dockerfile = 'proxy.Dockerfile'

[build.args]
  PUBLIC_PROTOCOL="https"
  PUBLIC_HOST="openrailwaymap.app"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  TILES_UPSTREAM_LOW = "ams.openrailwaymap-tiles.internal:3000"
  TILES_UPSTREAM_AFRICA = "ams.openrailwaymap-tiles-africa.internal:3000"
  TILES_UPSTREAM_ASIA = "ams.openrailwaymap-tiles-asia.internal:3000"
  TILES_UPSTREAM_EUROPE = "ams.openrailwaymap-tiles-europe.internal:3000"
  TILES_UPSTREAM_NORTH_AMERICA = "ams.openrailwaymap-tiles-north-america.internal:3000"
  TILES_UPSTREAM_OCEANIA = "ams.openrailwaymap-tiles-oceania.internal:3000"
  TILES_UPSTREAM_SOUTH_AMERICA = "ams.openrailwaymap-tiles-south-america.internal:3000"
  API_UPSTREAM = "ams.openrailwaymap-api.internal:5000"
  PUBLIC_PROTOCOL = "https"
  PUBLIC_HOST = "openrailwaymap.app"
  NGINX_RESOLVER = "[fdaa::3] valid=10m ipv6=on"
  NGINX_CACHE_TTL = "86400"
  CLIENT_CACHE_TTL_ASSETS_FRESH = "3600"
  CLIENT_CACHE_TTL_ASSETS_STALE = "604800"
  CLIENT_CACHE_TTL_API_FRESH = "8182"
  CLIENT_CACHE_TTL_API_STALE = "604800"
  CLIENT_CACHE_TTL_TILES_FRESH = "8182"
  CLIENT_CACHE_TTL_TILES_STALE = "604800"
  REWRITE_TILE_URLS = "false"
  RATELIMIT_ASSETS_PER_SECOND=1
  RATELIMIT_ASSETS_BURST=100
  RATELIMIT_API_PER_SECOND=1
  RATELIMIT_API_BURST=3
  RATELIMIT_TILES_PER_SECOND=10
  RATELIMIT_TILES_BURST=200

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
