name: Nightly update

on:
  workflow_dispatch: ~
  schedule:
    # Run daily at 17:47 UTC
    - cron: '47 17 * * *'

jobs:
  update-data:
    name: Update data
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull OSM data
        run: |
          docker pull ghcr.io/hiddewie/openrailwaymap-data:latest
          DB_CONTAINER_ID="$(docker container create ghcr.io/hiddewie/openrailwaymap-data:latest)"
          docker cp "$DB_CONTAINER_ID:/data/data.osm.pbf" data/filtered/data.osm.pbf

      - name: Update OSM data
        run: |
          docker compose run --build import update

      - name: Build new OSM data image
        run: |
          cat > .dockerignore << EOF
          **
          !data/filtered/data.osm.pbf
          EOF
          
          cat > Dockerfile << EOF
          FROM scratch
          COPY data/filtered/data.osm.pbf /data/data.osm.pbf
          EOF
          
          docker build --tag ghcr.io/hiddewie/openrailwaymap-data:latest

      - name: Push OSM data
        run: |
          docker push ghcr.io/hiddewie/openrailwaymap-data:latest
